### ISSUE TITLE
Create SMS Service on Twilio and connect it with Watson

### ISSUE THREAD

**Issue by smithjilks** [qualislabs/IBM-Call-for-code-2021-zero-hunger-solution#6]
# Requirements
1. Twilio and IBM Watson
2. The service should be able to recieve SMS messages, send them to Watson and get appropriate reply which will be sent back to the user.
3. This is basically an implementation of the android app functionality only that it is SMS based.
4. Refer to wire-frames for consistency.

# Tasks
- [ ] Create SMS service on Twilio.
- [ ] Create intents for Watson for analysis of incoming messages.
- [ ] Hook up Watson to appropriate Node-Red endpoints.
- [ ] Return appropriate responses to the user

**Comment by rodneyosodo** [comment]
Closing this issue due to inactivity. Please feel free to reopen if any further questions come up.
